services:
    vTamp:
        volumes:            
            - ./:/home/tapas
            - /tmp/.X11-unix:/tmp/.X11-unix
        user: "${CUSTUM_UID}:${CUSTUM_GID}"
        image: "miguelzamoram/tapas-container-cpu"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        command: /bin/bash
        environment:
            - DISPLAY=${DISPLAY}
            - HOME=/home/tapas
            - SHELL=/bin/bash
        container_name: tapasContainer
