services:
    vTamp:
        volumes:            
            - ./:/home/tapas
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /home/tapasdeveloper/Desktop/msc_thesis/wenkai/mujoco_simulation/unified_scene/replans/replan_data:/home/tapas/multi-agent-tamp-solver/24-data-gen/replan_data
        user: "${CUSTUM_UID}:${CUSTUM_GID}"
        image: "miguelzamoram/tapas-container-gpu"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        command: /bin/bash
        environment:
            - DISPLAY=${DISPLAY}
            - HOME=/home/tapas
            - SHELL=/bin/bash
        container_name: tapasContainer        
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['0']
                          capabilities: [gpu]
