env_name: "random" #"random" "husky" "conveyor" "shelf"
num_threads: 8
learning_rate: 1e-3
num_epochs: 10
evals_per_epoch: 5
batch_size: 128
num_shards: 8
train_samples_id: "*"
test_samples_id: "*"

testing:
    target_num_robots: 4
    target_num_objs: 3